### ISSUE TITLE
이슈 상세보기

### ISSUE THREAD

**Issue by Jinsujin** [Jinsujin/issue-tracker#2]
- [ ] 상단바에는 목록 버튼과 더보기 버튼이 있다
- [ ] 목록 버튼을 누르면 이슈 목록으로 돌아간다
- [ ] 더보기 버튼을 누르면 모달창이 뜬다
